WITH SUBMISSIONS AS (
    SELECT * FROM {{ ref("submission_seed") }}
),

RENAMED AS (
    SELECT
        ID AS RISK_ID,
        VERSION_NUMBER,
        RISK_PROCESSING_STATUS AS POLICY_STATUS,
        RISK_TYPE AS TRANSACTION_TYPE,
        CURRENT_VIEW_OF_RISK_ID,
        ANCESTOR_ID AS ANCESTOR_RISK_ID,
        SOURCE_EVENT_TIMESTAMP,
        LOG_INDEX
    FROM SUBMISSIONS
)

SELECT
    RISK_ID,
    row_number() OVER (PARTITION BY RISK_ID ORDER BY LOG_INDEX) AS SEQUENCE,
    VERSION_NUMBER,
    CASE
        WHEN TRANSACTION_TYPE = 'NEW' THEN RISK_ID
        WHEN TRANSACTION_TYPE = 'VERSIONED' THEN CURRENT_VIEW_OF_RISK_ID
        WHEN TRANSACTION_TYPE = 'MTA' THEN ANCESTOR_RISK_ID
        ELSE 00000
    END::INTEGER AS PARENT_RISK_ID
    ,
    POLICY_STATUS,
    TRANSACTION_TYPE,
    CURRENT_VIEW_OF_RISK_ID,
    ANCESTOR_RISK_ID,
    SOURCE_EVENT_TIMESTAMP
FROM RENAMED
