WITH SUBMISSIONS AS (
    SELECT * FROM {{ ref("submission_seed") }}
),

RENAMED AS (
    SELECT
        ID AS RISK_ID,
        VERSION_NUMBER,
        RISK_PROCESSING_STATUS AS POLICY_STATUS,
        RISK_TYPE AS TRANSACTION_TYPE,
        CURRENT_VIEW_OF_RISK_ID,
        ANCESTOR_ID AS ANCESTOR_RISK_ID,
        SOURCE_EVENT_TIMESTAMP
    FROM SUBMISSIONS
)

SELECT
    CASE
        WHEN TRANSACTION_TYPE = 'NEW' THEN RISK_ID
        WHEN TRANSACTION_TYPE = 'VERSIONED' THEN CURRENT_VIEW_OF_RISK_ID
        WHEN TRANSACTION_TYPE = 'MTA' THEN ANCESTOR_RISK_ID
        ELSE 'HAVE A LOOK'
    END::INTEGER AS PARENT_RISK_ID
    ,
    RISK_ID,
    VERSION_NUMBER,
    POLICY_STATUS,
    TRANSACTION_TYPE,
    CURRENT_VIEW_OF_RISK_ID,
    ANCESTOR_RISK_ID,
    SOURCE_EVENT_TIMESTAMP
FROM RENAMED
