WITH SUBMISSIONS AS (
    SELECT * FROM  {{ ref("submission_seed") }}
)
SELECT
ID as RISK_ID,
VERSION_NUMBER,
RISK_PROCESSING_STATUS AS POLICY_STATUS,
RISK_TYPE AS TRANSACTION_TYPE,
CURRENT_VIEW_OF_RISK_ID,
ANCESTOR_ID AS ANCESTOR_RISK_ID,
SOURCE_EVENT_TIMESTAMP,
FROM SUBMISSIONS